const __vite__mapDeps=(i,m=__vite__mapDeps,d=(m.f||(m.f=["MnemonicWordListing.js","index.js","index.css"])))=>i.map(i=>d[i]);
import{c as l,a0 as x,a1 as y,x as j,r as w,_ as f,j as e,C as g,d as b,e as D,f as k,g as v,h as C,B as a}from"./index.js";import{D as N,a as M,b as T,c as L,d as _,g as H,e as R,f as S}from"./Dialog.js";import{A as c}from"./arrow-right.js";import"./index2.js";import"./x.js";/**
 * @license lucide-react v0.400.0 - ISC
 *
 * This source code is licensed under the ISC license.
 * See the LICENSE file in the root directory of this source tree.
 */const B=l("HardDriveDownload",[["path",{d:"M12 2v8",key:"1q4o3n"}],["path",{d:"m16 6-4 4-4-4",key:"6wukr"}],["rect",{width:"20",height:"8",x:"2",y:"14",rx:"2",key:"w68u3i"}],["path",{d:"M6 18h.01",key:"uhywen"}],["path",{d:"M10 18h.01",key:"h775k"}]]);/**
 * @license lucide-react v0.400.0 - ISC
 *
 * This source code is licensed under the ISC license.
 * See the LICENSE file in the root directory of this source tree.
 */const E=l("Undo",[["path",{d:"M3 7v6h6",key:"1v2h90"}],["path",{d:"M21 17a9 9 0 0 0-9-9 9 9 0 0 0-6 2.3L3 13",key:"1r6uu6"}]]),O=o=>{if(!o)return"";const t=o.trim();if(!t)return"";const s=x.Buffer.from(t.substring(2),"hex");return y.SeedBinToMnemonic(s)},P=j(w.lazy(()=>f(()=>import("./MnemonicWordListing.js"),__vite__mapDeps([0,1,2])))),Z=({account:o,onMnemonicNoted:t})=>{const s=o==null?void 0:o.address,d=o==null?void 0:o.seed,r=O(d),h=()=>{const u=JSON.stringify({"Public Address":{address:s,note:"This is your public account address, and can be shared with others for receiving ZND to your account."},"Private Key":{key:r,note:"This is your secret private key(mnemomic phrases, a 32 words combination), and should be kept safe somewhere. This is required to recover your account and to send ZND from your account to others account. If lost, you will lose access to your account and funds."}},null,2),p=new Blob([u],{type:"application/json"}),i=URL.createObjectURL(p),n=document.createElement("a");n.href=i,n.download="Secret Mnemonic Phrases.json",document.body.appendChild(n),n.click(),document.body.removeChild(n),URL.revokeObjectURL(i)},m=`Don't lose this mnemonic phrases. Download it right now. You may need this someday to import or recover your new account ${s==null?void 0:s.substring(0,6)} ... ${s==null?void 0:s.substring((s==null?void 0:s.length)-5)}`;return e.jsxs(g,{className:"text-ellipsis",children:[e.jsxs(b,{children:[e.jsx(D,{children:"Keep this safe"}),e.jsx(k,{children:m})]}),e.jsx(v,{children:e.jsx(P,{mnemonic:r})}),e.jsxs(C,{className:"gap-4",children:[e.jsxs(a,{className:"w-full",type:"button",variant:"constructive",onClick:h,children:[e.jsx(B,{className:"mr-2 h-4 w-4"}),"Download"]}),e.jsxs(N,{children:[e.jsx(M,{asChild:!0,children:e.jsxs(a,{className:"w-full",type:"button",children:[e.jsx(c,{className:"mr-2 h-4 w-4"}),"Continue"]})}),e.jsxs(T,{className:"w-80 rounded-md",children:[e.jsxs(L,{className:"text-left",children:[e.jsx(_,{children:"Important!"}),e.jsx(H,{children:"You should only continue if you have downloaded the mnemonic phrases. If you haven't, go back, download, and then continue. There is no going back once you click the continue button."})]}),e.jsxs(R,{className:"flex flex-row gap-4",children:[e.jsx(S,{asChild:!0,children:e.jsxs(a,{className:"w-full",type:"button",variant:"outline",children:[e.jsx(E,{className:"mr-2 h-4 w-4"}),"Go back"]})}),e.jsxs(a,{className:"w-full",type:"button",onClick:t,children:[e.jsx(c,{className:"mr-2 h-4 w-4"}),"Continue"]})]})]})]})]})]})};export{Z as default};
